streamcat_tables = ["Runoff",
                    "Pesticides97",
                    "PRISM_1981_2010",
                    "NLCD2006",
                    "Kffact",
                    "ImperviousSurfaces2006",
                    "CanalDensity",
                    "BFI",
                    "AgMidHiSlopes",
                    "Elevation"]

compounds = ["CHLORPYRIFOS"]

nhd_states = {'01': {"ME", "NH", "VT", "MA", "CT", "RI", "NY"},
            '02': {"VT", "NY", "PA", "NJ", "MD", "DE", "WV", "DC", "VA"},
            '03N': {"VA", "NC", "SC", "GA"},
            '03S': {"FL", "GA"},
            '03W': {"FL", "GA", "TN", "AL", "MS"},
            '04': {"WI", "MN", "MI", "IL", "IN", "OH", "PA", "NY"},
            '05': {"IL", "IN", "OH", "PA", "WV", "VA", "KY", "TN"},
            '06': {"VA", "KY", "TN", "NC", "GA", "AL", "MS"},
            '07': {"MN", "WI", "SD", "IA", "IL", "MO", "IN"},
            '08': {"MO", "KY", "TN", "AR", "MS", "LA"},
            '09': {"ND", "MN", "SD"},
            '10U': {"MT", "ND", "WY", "SD", "MN", "NE", "IA"},
            '10L': {"CO", "WY", "MN", "NE", "IA", "KS", "MO"},
            '11': {"CO", "KS", "MO", "NM", "TX", "OK", "AR", "LA"},
            '12': {"NM", "TX", "LA"},
            '13': {"CO", "NM", "TX"},
            '14': {"WY", "UT", "CO", "AZ", "NM"},
            '15': {"NV", "UT", "AZ", "NM", "CA"},
            '16': {"CA", "OR", "ID", "WY", "NV", "UT"},
            '17': {"WA", "ID", "MT", "OR", "WY", "UT", "NV"},
            '18': {"OR", "NV", "CA"}}
